### ISSUE TITLE
kswitch args and get current zone

### ISSUE THREAD

**Issue by ymettier** [Caascad/toolbox#21]
```
$ kswitch
```
No args -> error (and help)

What about returning the current zone ?

Or have a specific arg to print the current zone (don't forget to add it in the help message)

**Comment by eonpatapon** [comment]
What about something like that ?
```
$ kswitch
--- Current context is ocb-sbma
--- Tunnel is active (pid=30752)
--- Tunneling through cloud@bst.ocb-sbma.caascad.com

$ kswitch
--- Current context is ocb-sbma
--- Tunnel is down: run kswitch ocb-sbma
```

**Comment by ymettier** [comment]
Nice :+1: 

And another one : 
```
$ kswitch --output=short
ocb-sbma
```
I don't care about the arg name and value. The idea is to get a short value that a script can use. For example : my prompt where I would put something like `PS1='$(kswitch --output=short)% '`

**Comment by eonpatapon** [comment]
You can get the context only with `kubectl config current-context`
